finalized systemd abstractions and tests and support, now may kill terminal session on exit, we'll see

diff --git a/sgfxi b/sgfxi
--- a/sgfxi
+++ b/sgfxi
@@ -3,10 +3,10 @@
 ####  Script Name: simple/system graphics installer: sgfxi
 ####  Debian Sid, Testing, and Stable graphic driver install.
 ####  New: Ubuntu support in progress. Arch/Fedora Support under development
-####  version: 4.21.25
-####  Date: 2013-12-26
+####  version: 4.22.00
+####  Date: 2014-01-01
 ########################################################################
-####  Copyright (C) Harald Hope 2007-2013
+####  Copyright (C) Harald Hope 2007-2014
 ####  Code contributions copyright: Latino 2008
 ####  Contributors: ati card driver and xorg configuration in general: damentz and d2kx
 ####  function check_ia32_libs by Steven Barrett (damentz, maintainer of zen/liquorix projects).
@@ -7383,7 +7383,7 @@ start_stop_x()
 	# default, this prevents errors when these don't exist in for ex. fedora
 	local serviceControl='/etc/init.d/' startPath='/etc/init.d/' bSkipXKill='false'
 	local noHup='nohup' xActionString='' finalXKill='' dmanCommand=''
-	local gdmCommand='' bSkipLoop='
+	local gdmCommand='' bSkipLoop='ttyKill=0
 	local defaultDM=$( get_default_display_manager )
 	if [ -z "$defaultDM" ];then
 		defaultDM=$( do_display_manager_pid_test )
@@ -7510,8 +7510,13 @@ start_stop_x()
 		if [ "$B_SM_INSTALL" != 'true' ];then
 			# the failure case handels a weird thing when kill gives error
 			if [ -n "$LOGIN_PID" ];then
-				if [ -n "$defaultRunlevel" ];then
-					init $defaultRunlevel && kill $LOGIN_PID && exit 0 || exit 1
+		"$B_SYSTEMD" == 'true' ];then
+					kill_systemd_tty || ttyKill=$?
+					if [ "$ttyKill" -gt 0 ];then
+						kill $LOGIN_PID && exit 0 || exit 1
+					fi
+				elif [ -n "$defaultRunlevel" ];then
+					init $INIT_LEVELunlevel && kill $LOGIN_PID && exit 0 || exit 1
 				else
 					kill $LOGIN_PID && exit 0 || exit 1
 				fi
@@ -7599,6 +7604,41 @@ get_default_display_manager()
 
 	echo $defaultDM
 	log_function_data "defaultDM: $defaultDM"$return
+	eval $LOkill_systemd_tty()
+{
+	eval $LOGUS
+	local returnValue=1 ttyStatus=''
+	local scriptTTY=$(get_current_tty)
+	
+	# verify we have an actual tty valid type
+	if [ -n "$scriptTTY" -a -n "$( grep -E '^tty[0-9]+$' <<< $scriptTTY )" ];then
+		ttyStatus="$( systemctl status getty@$scriptTTY.service )"
+		log_function_data "ttyStatus:\n$ttyStatus"
+		# double check it's the tty running script, then make sure that tty is actually active
+		if [ -n "$( grep "$SCRIPT_NAME" <<< "$ttyStatus" )" ];then
+			if "$( grep -Esi 'Active:[[:space:]]*active' <<< "$ttyStatus" )" ];then
+				echo "${M}Systemd being used to attempt to exit tty${N}"
+				systemctl stop getty@$scriptTTY.service
+				returnValue=$?
+			fi
+		fi
+	fi
+	# in theory this should not be running anymore so nothing to log, but we'll do it for errors
+	log_function_data "returnValue: $returnValue"
+	return $returnValue
+	eval $LOGUE
+}
+
+get_current_tty()
+{
+	eval $LOGUS
+	
+	local term=$( basename tty )
+	term=$( basename $term )
+	
+	log_function_data "term: $term"
+	echo $term
+	$return
 	eval $LOGUE
 }
 
@@ -8568,7 +8608,7 @@ get_options()
 				;;
 			W) B_SKIP_WGET='true'
 				START_OPTIONS=$START_OPTIONS' -W'
-				START_OPTIONS_PRINT="$START_OPTIONS_PRINT  -W - Skip wget downloads. Only use if you are having problems connecting\n    but you have the current driver downloaded a Not recommended!lready.\n"
+				START_OPTIONS_PSTART_OPTIONS_PRINT  -W - Skip wget downloads. Only use if you are having problems connecting\n    but you have the current driver downloaded already. Not recommended!\n"
 				;;
 			x) B_NO_XVMC='true' # because two flags are required to use nvidia xvmc, this is fine
 				START_OPTIONS=$START_OPTIONS' -x'
@@ -8594,7 +8634,7 @@ get_options()
 				;;
 			H)	show_options 'full'
 				;;
-			## debuggers and testions
+			## debuggers and testing options
 			!)	# test for various supported methods
 				bSkipOutput=''
 				case $OPTARG in
