new amd/fglrx beta, once again, they have psychotically changed, for no reason, their f'ing file names/paths, proving as if it needed proving that this company should be avoided like the plague if you want working non free video drivers long term.
They clearly have nobody technically competent running this linux group, don't risk it.

diff --git a/sgfxi b/sgfxi
--- a/sgfxi
+++ b/sgfxi
@@ -3,8 +3,8 @@
 ####  Script Name: simple/system graphics installer: sgfxi
 ####  Debian Sid, Testing, and Stable graphic driver install.
 ####  New: Ubuntu support in progress. Arch/Fedora Support under development
-####  version: 4.20.53
-####  Date: August 5 2013
+####  version: 4.20.54
+####  Date: August 16 2013
 ########################################################################
 ####  Copyright (C) Harald Hope 2007-2013
 ####  Code contributions copyright: Latino 2008
@@ -294,12 +294,26 @@ NV_64_ARCH='' # if nvidia changes file name use this
 # note, as distressingly usual, amd AGAIN has changed their driver name syntax. 
 FG_VERSIONS='13-4:13.1:12.10'
 FG_DEFAULT='13-4'
+# amd has no discipline whatsoever, look at the ridiculous failure to name the f#cking download file
+# consistently release to release, clearly this organization is run by incompetents of the highest order.
+# hint: use real package numbering and you avoid all this 'legacy/beta' nonsense.
+# amd-driver-installer-12-8-x86.x86_64.zip
+# amd-driver-installer-catalyst-12.10-x86.x86_64.zip
+# amd-driver-installer-catalyst-13.1-linux-x86.x86_64.zip
+# amd-driver-installer-catalyst-13.3-beta3-linux-x86.x86_64.zip
+# amd-driver-installer-catalyst-13-4-linux-x86.x86_64.zip
+# amd-driver-installer-catalyst-13-6-beta-x86.x86_64.zip
+# amd-catalyst-13.8-beta1-linux-x86.x86_64.zip 
 # http://www2.ati.com/drivers/legacy/amd-driver-installer-catalyst-13.1-legacy-linux-x86.x86_64.zip
 FG_LEGACY_2='' # random releases/xorg support, hard to follow. note as of 2012-1, legacy uses changed paths
 # http://www2.ati.com/drivers/beta/amd-driver-installer-catalyst-12.11-beta-x86.x86_64.zip
 # http://www2.ati.com/drivers/linux/amd-driver-installer-catalyst-12.10-x86.x86_64.zip
 # http://www2.ati.com/drivers/beta/amd-driver-installer-catalyst-13.2-beta3-linux-x86.x86_64.zip
 # http://www2.ati.com/drivers/beta/amd-driver-installer-catalyst-13-6-beta-x86.x86_64.zip
+
+# http://www2.ati.com/drivers/beta/amd-driver-installer-catalyst-13-6-beta-x86.x86_64.zip 
+# http://www2.ati.com/drivers/beta/amd-catalyst-13.8-beta1-linux-x86.x86_64.zip 
+
 FG_DEFAULT_BETA='13-6'
 FG_BETA_VERSION='beta'
 FGLRX_PACKAGE_PREFIX='' # set to amd or ati, amd is for >= 12-1
@@ -455,10 +469,10 @@ driver_support_tests()
 						esac
 					fi
 					case $DRIVER_DEFAULT in
-# 						13[-.][4-9]|13[-.]1[0-2]|14[-.]*|15[-.]*)
-# 							FGLRX_PACKAGE_PREFIX='amd-catalyst'
-# 							;;
-						13[-.][4-9]|13[-.]1[0-2]|14[-.]*|15[-.]*)
+						13[-.][8-9]|13[-.]1[0-2]|14[-.]*|15[-.]*)
+							FGLRX_PACKAGE_PREFIX='amd-catalyst'
+							;;
+						13[-.][4-6])
 							FGLRX_PACKAGE_PREFIX='amd-driver-installer-catalyst'
 							;;
 						12[-.]1[0-2]|13[-.][0-3])
@@ -1753,11 +1767,11 @@ set_test_data()
 		rm -f $SCRIPT_NAME.log
 # 		# sgfxi doesn't support any legacy ATI stuff
 # 		CARD_DATA=1002:7280 # fake ati pre x2000 card
-# 		CARD_DATA=1002:9442 # fake ati hd2000-# 4xxx
+# 		CARD_DATA=1002:9442 # fake ati hd2000-4xxx
 # 		CARD_DATA=1002:9805 # fake ati hd 6250 card
 # 		CARD_DATA=10de:0020 # fake nvidia oldest legacy (7x.xx.xx dr# ers)
 # 		CARD_DATA=10de:0280 # fake nvidia mid legacy (9x.xx.xx dr# ers)
-# 		CARD_DATA=10de:0322 # fake nvidia 5xxx legacy (173.xx.xx drivers)
+# 		CARD_DATA=10de:0322 # fake nvidia 5xxx legacy (173.xx.xx dr# ivers)
 		CARD_DATA=10de:0392 # fake nvidia 7xxx legacy (304.xx drivers)
 # 		CARD_DATA=10de:0422 # fake nvidia current card (GS 8400)
 # 		FG_DEFAULT='8-5'
@@ -2413,8 +2427,9 @@ detect_card_version()
 					# if no working driver via standard ati installer. Here we're also handling
 					# the monthly releases, so users can do an experimental test if needed
 					# if [ "$B_DISTRO_FLAG" == 'true' -a "$B_TESTING_1" != 'true' ]
-					LEGACY_LEVEL=100
-					DRIVER_DEFAULT=$( assign_standard_or_beta_driver 'default' 'driver' # echo 'dd: ' $DRIVER_DEFAULT
+					LEGACY_LEVEL=10# this will reset the globals for betas/default drivers. Must not run in subshell
+					assign_standard_or_beta_driver 'default' 'driver'
+					iver' # echo 'dd: ' $DRIVER_DEFAULT
 					B_BETA_EXISTS=$( assign_standard_or_beta_driver 'default' 'set-exists' )
 					# echo 'be: ' $B_BETA_EXISTS0 cards
 					if [ "$B_DISTRO_FLAG" == 'true' ];then
@@ -2433,10 +2448,7 @@ detect_card_version()
 			B_NATIVE_DRIVER='true'
 			;;
 	esac
-	#echo $cardNumber
-}
-
-# this is only for nVidia cards so no need to do testing
+	#echo $cardNumbenote that for fglrx we need to just change the global values, not run this as subshell for driver teststesting
 # args: $1 - default/leg4cy-[1-3]; $2 - set-exists/driver
 assign_standard_or_beta_driver()
 {
@@ -2516,15 +2528,17 @@ assign_standard_or_beta_driver()
 				liveBetas=$( gebeta_drivers )
 				if [ "$bDebugger" == 'true' ];then
 					echo
+					echo "Start assign_standard_or_beta_driver"
 					echo "lb:$liveBetas:"
 				fi
 				
 				if [ -n "$liveBetas" ];then
 					# check for spastic amd version numbering here, 13-6 vs 13.4
-					if [ -n $( grep -E '^[0-9]+-[0-9]+' <<< "$liveBetas" ) ];then
+					# note, make sure to use [[ for null cases here
+					if [[ -n $( grep -E '^[0-9]+-[0-9]+' <<< "$liveBetas" ) ]];then
 						betaCurrent=$( cut -d '-' -f 1,2 <<< "$liveBetas" )
 						betaVersion=$( cut -d '-' -f 3 <<< "$liveBetas" )
-					elif [ -n $( grep -E '^[0-9]+\.[0-9]+' <<< "$liveBetas" ) ];then
+					elif [[ -n $( grep -E '^[0-9]+\.[0-9]+' <<< "$liveBetas" ) ]];then
 						betaCurrent=$( cut -d '-' -f 1 <<< "$liveBetas" )
 						betaVersion=$( cut -d '-' -f 2 <<< "$liveBetas" )
 					fi
@@ -2554,21 +2568,40 @@ assign_standard_or_beta_driver()
 					-a -n "$defaultBetaVersion" -a "$( compare_numbers $betaCurrentVersionWorking $defaultBetaVersion )" -eq 0  ];then
 						FG_DEFAULT_BETA=$betaCurrent
 						FG_BETA_VERSION=$betaVersion
+						# echo yest1
 					fi
 				fi
 			fi
 			if [ -n "$FG_DEFAULT_BETA" -a "$( compare_numbers $defaultBetaWorking $FG_DEFAULT )" -eq 0T_BETA" ];then
 				betaDriver=$FG_DEFAULT_Bfi
+			if [ "$bDebugger" == 'true' ];then
+				echo "FDB:$FG_DEFAULT_BETA:"
+				echo "FBV:$FG_BETA_VERSION:"
+				echo "bd:$betaDriver:"
+				echo "End assign_standard_or_beta_driver"LT_Bfi
 			stableDriver=$FG_DEFAULTT
 			fi
 			;;
 	esac
 
 	if [ "$2" == 'driver' ];then
-		if [ -n "$betaDriver" -a "$B_USE_BETA" == 'true' ];then
-			echo $betaDriver
+		if [ -n "$betaDriver" -a "$B_USE_BETA" == 'true' ];tcase $CARD in
+				$NVIDIA)
+					echo $betaDriver
+					;;
+				$FGLRX)
+					DRIVER_DEFAULT=$betaDriver
+					;;
+			esac
 		elif [ -z "$betaDriver" -o "$B_USE_BETA" != 'true' ];then
-			echo $stableDriver
+			case $CARD in
+				$NVIDIA)
+					echo $stableDriver
+					;;
+				$FGLRX)
+					DRIVER_DEFAULT=$stableDriver
+					;;
+			esaceDriver
 		fi
 	else
 		if [ -n "$betaDriver" -a "$B_USE_BETA" == 'true' ];then
@@ -2710,7 +2743,7 @@ create_data_storage()
 		echo $LINE
 		echo "${S}Creating ${C}$SCRIPT_WORKING_DIR${S} to store driver downloads in...${N}"
 		mkdir -p $SCRIPT_WORKING_DIR
-		rm -f ${USRS}nohup.out &>/dev/null # sometimes these get left over...
+		rm -f ${USRS}nohup.out &>/d # sometimes these get left over...
 		rm -rf /usr/src/nvidia-installer &>/dev/null # this can cause weirdness so dump it
 		nvidiaPackages=$( ls ${USRS} 2>/dev/null | grep -Esi '^nvidia' )
 		nvidiaPackages=$( echo $nvidiaPackages )
@@ -2752,7 +2785,7 @@ clean_script_data()
 
 	local downloadDirectorySize='' backupFiles='' backupFilesCount=''
 	local opt='' bRepeat='false'
-	local options="remove-video-driver-downloads delete-xorg.conf-backup-files uninstall-$SCRI quit" 
+	local options="remove-video-driver-downloads delete-xorg.conf-backup-files uninstall-$SCRIPT_NAME quit" 
 	
 	echo $MLINE
 	echo "${M}$SCRIPT_NAME cleanup tool"
@@ -2934,7 +2967,7 @@ check_kernel_headers()
 				echo "${S}Installing missing kernel header package ${C}$headerName${S} before proceeding...${N}"
 				install_package "$headerName"
 			elif [ -z "$headerInstalled" -a -n "$headerFile" -a -f "$headerFile" ];then
-				echo "${S}Installing missing kernel header package ${C}$headerName${S}"
+				echo "${S}Installing missing kernel header package ${C}$headerName${S}"fse
 				echo "using your archived header package: ${C}$headerFile${N}"
 				dpkg -i $headerFile || error_handler 223 "$headerFile"
 			elif [ -z "$headerInstalled" -a -z "$headerAvailable" -a "$B_TESTING_5" != 'true' ];then
@@ -5092,7 +5125,7 @@ set_driver_install_version()
 {
 	eval $LOGPS
 	local response='' printDriver='' newKernelText='' betaDriverText=''
-	local moduleOrInstall='inst extraBetaInfo='talling'
+	local moduleOrInstall='inst extraBetaInfo='ta	local bDebugger='falsetalling'
 
 	# I'm forcing special cases to override the defaults so the data
 	# printed out will show what drivers are supported
@@ -5143,7 +5176,12 @@ set_driver_install_version()
 	if [ "$B_USE_BETA" == 'true' ];then
 		case $CARD in
 			$NVIDIA|$FGLRX)
-				if [ "$B_BETA_EXISTS" == 'true' ];then
+				if [ "$B_BETA_EXISTS" == 'true' ];theif [ "$bDebugger" == 'true' ];then
+						echo "FDB:$FG_DEFAULT_BETA:"
+						echo "FBV:$FG_BETA_VERSION:"
+						echo "bd:$betaDriver:"
+						echo "End assign_standard_or_beta_driver"
+					fi ];then
 					betaDriverText="\n${M}This is the latest ${C}$CARD Beta driver${M} for your card type.${N}\	if [ "$CARD" == $FGLRX ];then
 						extraBetaInfo=" ($FG_BETA_VERSION) "
 					fi${N}\n"
@@ -5243,8 +5281,15 @@ set_download_info()
 			if [ "$B_USE_BETA" == 'true' ];th# note: need beta* because amd releases numbered betas within a month release ];th# # http://www2.ati.com/drivers/beta/amd-driver-installer-catalyst-13.3-beta3-linux-x86.x86_64.zip
 				# http://www2.ati.com/drivers/beta/amd-driver-installer-catalyst-13-6-beta-x86.x86_64.zip
 				# amd-catalyst-13.6-beta-linux-x86.x86_64.run
+				
 				fgBetaVersion="-$FG_BETA_VERSION"'beta-'
-				downloadUrl='http://www2.ati.com/drivers/bet	FG_POST='s/beta/'
+				downloadUrl='http://www2.ati.com/drivers/bet	# note, amd changed this AGAIN!!! for their damned betas
+				# www2.ati.com/drivers/beta/amd-catalyst-13.8-beta1-linux-x86.x86_64.zip 
+				# www2.ati.com/drivers/beta/amd-driver-installer-catalyst-13-6-beta-x86.x86_64.zip 
+				# DO NOT BUY AMD CARDS if you want competent nonfree video driver support!!!
+				if [ "$DRIVER_DEFAULT" == '13.6' ];then
+					FG_POST=''
+				fi/beta/'
 			else
 				downloadUrl='http://www2.ati.com/drivers/linux/'
 			fi
@@ -5798,7 +5843,7 @@ install_libvdpau()
 	esac
 	
 	if [ "$B_TESTING_5" != 'true' -a -n "$libVdPau" -a "$LEGACY_LEVEL" -gt 3 ];then
-		if [ -z "$( check_package_status "$libVdPau" 'i' )" ];then
+		if [ -heck_package_status "$libVdPau" 'i' )" ];then
 			if [ -n "$( check_package_status "$libVdPau" 'c' )" ];then
 				install_package "$libVdPau"
 			fi
@@ -5837,7 +5882,7 @@ post_installer_steps()
 						if [ -n "$( check_package_status 'mesa' 'c' )" ];then
 							install_package 'mesa'
 						fi
-					fi
+					filer 176
 					;;
 			esac
 			;;
@@ -5845,11 +5890,8 @@ post_installer_steps()
 	eval $LOGPE
 }
 
-### -------------------------------------------------------------------
-### module tools
-### -------------------------------------------------------------------
-
-# $1 - direct/build; $2 - silent [optional]
+### -----------------------------------------------------------------module toolng steps
+### ----------------------------------------------------------------$1 - direct/build; $2 - silent [optional]
 build_kernel_module_only()
 {
 	eval $LOGPS
@@ -5872,7 +5914,7 @@ build_kernel_module_only()
 			echo $LINE
 			echo "${S}Building kernel module ${C}$DRIVER_DEFAULT${S} for kernel ${C}$KERNEL_FULL${S} now (can take a while)...${N}"
 			if [ "$2" != 'silent' ];then
-				bash $SCRIPT_WORKING_DIR/$runPacklent -N --kernel-name=$KERNEL_FULL --kernel-module-only -a || moduleResult=$?
+				bash $SCRIPT_WORKING_DIR/$runPackage $silent -N --kernel-name=$KERNEL_FULL --kernel-module-only -a || moduleResult=$?
 			else
 				silent=' -s'
 				bash $SCRIPT_WORKING_DIR/$runPackage $silent -N --kernel-name=$KERNEL_FULL --kernel-module-only -a 1>> $LOG_FILE 2>> $LOG_FILE || moduleResult=$?
